apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis:{{ .Values.redis.service.port }}/0"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: release-maintainer-secrets
                  key: github_token
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: release-maintainer-secrets
                  key: jwt_secret_key
            - name: SEED_USERS
              valueFrom:
                secretKeyRef:
                  name: release-maintainer-secrets
                  key: seed_users
