helm:
  parameters:
  - name: backend.image.repository
    value: ghcr.io/justme0606/release-maintainer-backend
    forcestring: true
  - name: backend.image.tag
    value: latest@sha256:c62de1f9a83d30e954c542fd4471ea9e7bf375868a3dc145d441307e327252c9
    forcestring: true
  - name: frontend.image.repository
    value: ghcr.io/justme0606/release-maintainer-frontend
    forcestring: true
  - name: frontend.image.tag
    value: latest@sha256:707d0a4880ee1301981b9fcfb116988bc3dbfbf3ef9409c00c5da21868e4f144
    forcestring: true
