helm:
  parameters:
  - name: backend.image.repository
    value: ghcr.io/justme0606/release-maintainer-backend
    forcestring: true
  - name: backend.image.tag
    value: latest@sha256:f6010f3e6a67881abaf003c7f1c3d3304bf7915a79f3aabfb29c66b7db25b6ac
    forcestring: true
  - name: frontend.image.repository
    value: ghcr.io/justme0606/release-maintainer-frontend
    forcestring: true
  - name: frontend.image.tag
    value: latest@sha256:2f546e549c5b4d148d64c254f34171f9c81d498b56a50be64076ec9ad0b8fff5
    forcestring: true
