helm:
  parameters:
  - name: backend.image.repository
    value: ghcr.io/justme0606/release-maintainer-backend
    forcestring: true
  - name: backend.image.tag
    value: latest@sha256:16586f8f864ec86f9480efce839a786ed24e86ea819a8a4e2395e11a32d7b4f9
    forcestring: true
  - name: frontend.image.repository
    value: ghcr.io/justme0606/release-maintainer-frontend
    forcestring: true
  - name: frontend.image.tag
    value: latest@sha256:a02213e1bfa66c2fe6f33bd67ba3d7a9ed59713232e64beee0f878ca96acf797
    forcestring: true
