frontend:
  image:
    repository: ghcr.io/justme0606/release-maintainer-frontend
    tag: sha-0eb5dc5
    pullPolicy: Always
  service:
    port: 80

backend:
  image:
    repository: ghcr.io/justme0606/release-maintainer-backend
    tag: sha-0eb5dc5
    pullPolicy: Always
  service:
    port: 8000

redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 6379

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: rocq-dashboard.web-together.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: release-maintainer-tls
      hosts:
        - rocq-dashboard.web-together.com