name: Build and Push Docker images

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "charts/release-maintainer/.argocd-source-release-maintainer.yaml"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: frontend
            context: ./frontend
            image: ghcr.io/justme0606/release-maintainer-frontend
          - name: backend
            context: ./backend
            image: ghcr.io/justme0606/release-maintainer-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=develop,enable=${{ github.ref == 'refs/heads/develop' }}
            type=sha,prefix=sha-

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
